openapi: 3.0.3
info:
  title: Users API
  version: 1.0.0

paths:
  /api/users:
    get:
      operationId: getAllUsers
      tags: [users]
      summary: List all users (ADMIN only)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
        '403':
          description: Forbidden

  /api/users/{id}:
    get:
      operationId: getUserById
      tags: [users]
      summary: Get user by ID (ADMIN or own profile)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '403':
          description: Forbidden
        '404':
          description: User not found

    put:
      operationId: updateUser
      tags: [users]
      summary: Update user profile (ADMIN or own profile)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '403':
          description: Forbidden
        '404':
          description: User not found

    delete:
      operationId: deleteUser
      tags: [users]
      summary: Delete user (ADMIN only)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted
        '403':
          description: Forbidden
        '404':
          description: User not found

  /api/users/{id}/role:
    put:
      operationId: updateUserRole
      tags: [users]
      summary: Change user role (ADMIN only)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoleRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '403':
          description: Forbidden
        '404':
          description: User not found

  /api/users/me:
    get:
      operationId: getCurrentUser
      tags: [users]
      summary: Get current authenticated user profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

  /api/users/me/password:
    put:
      operationId: changePassword
      tags: [users]
      summary: Change own password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: Password changed
        '400':
          description: Invalid old password

components:
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        name:
          type: string
        email:
          type: string
        role:
          type: string

    UpdateUserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string

    UpdateRoleRequest:
      type: object
      required:
        - role
      properties:
        role:
          type: string
          enum:
            - USER
            - ADMIN

    ChangePasswordRequest:
      type: object
      required:
        - oldPassword
        - newPassword
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
          minLength: 6
